# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT oc.wsgi

beta_settings:
    cloud_sql_instances: opencurrents-194003:us-central1:oc-pg

runtime_config:
 python_version: 2
# [END runtime]
